---
version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  pull-request-branch-name:
    separator: "-"
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "daily"
  pull-request-branch-name:
    separator: "-"
