#!/bin/sh

set -eu

PROJECT_DIR=$(cd "$(dirname "$0")/../" && pwd)
CURRENT_DIR=$(pwd)

export CF_API
export CF_APPS_DOMAIN

cd ${PROJECT_DIR}/redirect

echo "Creating paas-tech-docs-redirect manifest"
${PROJECT_DIR}/release/generate-redirect-manifest \
    < manifest.yml \
    > modified_manifest.yml

echo "Deploying ${CF_APP_NAME}-redirect with zero downtime"
cf zero-downtime-push ${CF_APP_NAME}-redirect \
    -f modified_manifest.yml

cd ${CURRENT_DIR}
