#!/bin/sh

set -eu

echo "Creating manifest"
export CF_API
export CF_APPS_DOMAIN
release/generate-manifest \
    < manifest.yml \
    > modified_manifest.yml

echo "Deploy with zero downtime"
cf zero-downtime-push paas-tech-docs \
    -f modified_manifest.yml
