#!/bin/sh

set -eu

# Note: the app name must be kept in sync with the name inside manifest.yml
echo Deploy with zero downtime
cf blue-green-deploy paas-tech-docs

echo Delete left over app
cf delete -f paas-tech-docs-old
