---
name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_VERSION: "12.x"
  PYTHON_VERSION: "3.x"

jobs:
  deploy:
    name: Deploy Tech Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: "${{env.NODE_VERSION}}"

      - name: Setup Ruby
        uses: ruby/setup-ruby@5f19ec79cedfadb78ab837f95b87734d0003c899
        with:
          bundler-cache: true

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - name: Install Python and Node dependencies
        run: |
          npm ci
          pip install --user -r requirements.txt

      - name: Node tests
        run: npm test

      - name: Python tests
        run: |
          gem install webrick
          make test

      - name: Build middleman site
        run: make build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: 'build'

      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e

      - name: Slack notify on failure
        if: failure()
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52
        with:
          payload: |
            {
              "text": "Deployment of Paas Tech Docs with commit ${{ github.sha }} FAILED."
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK