---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "12.x"
  PYTHON_VERSION: "3.x"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@6615b4b8a02c78c4d711c06df4b8a20aa685a45d
        with:
          bundler-cache: true

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: npm ci
      - run: pip install --user -r requirements.txt

      - name: Node tests
        run: npm test

      - name: Python tests
        run: |
            gem install webrick
            make test
