---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "12.x"
  PYTHON_VERSION: "3.x"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@472790540115ce5bd69d399a020189a8c87d641f
        with:
          bundler-cache: true

      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: npm ci
      - run: pip install --user -r requirements.txt

      - name: Node tests
        run: npm test

      - name: Python tests
        run: |
            gem install webrick
            make test
