---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "12.x"
  PYTHON_VERSION: "3.x"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47
        with:
          bundler-cache: true

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: npm ci
      - run: pip install --user -r requirements.txt

      - name: Node tests
        run: npm test

      - name: Python tests
        run: |
            gem install webrick
            make test
