---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "12.x"
  PYTHON_VERSION: "3.x"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42
        with:
          bundler-cache: true

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: npm ci
      - run: pip install --user -r requirements.txt

      - name: Node tests
        run: npm test

      - name: Python tests
        run: |
            gem install webrick
            make test
