---
name: pr-tests
on: pull_request

env:
  NODE_VERSION: "12.x"
  PYTHON_VERSION: "3.x"
  NODE_ENV: development

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: "${{env.NODE_VERSION}}"

      - uses: ruby/setup-ruby@d3c9825d67b0d8720afdfdde5af56c79fdb38d16
        with:
          bundler-cache: true

      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0
        with:
          python-version: "${{env.PYTHON_VERSION}}"

      - run: npm ci
      - run: pip install --user -r requirements.txt

      - name: Node tests
        run: npm test

      - name: Python tests
        run: |
            gem install webrick
            make test
